server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/acvsystem?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: localhost  # 改为2个空格缩进
    port: 6379       # 改为2个空格缩进
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

aliyun:
  oss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tRmon4iHzyoAonjXCwJ
    access-key-secret: NLA9KWHOSvZhF4APNuXVaTUhGxjNga
    bucket-name: acvs
    region: cn-guangzhou

swagger:
  enabled: true

